In [0]:
import matplotlib.pyplot as plt
import numpy as np
import copy
import math
import csv
from google.colab import files

In [2]:
uploaded = files.upload()

Saving mnist.csv to mnist.csv


In [6]:
file_data   = "mnist.csv"
handle_file = open(file_data, "r")
data        = handle_file.readlines()
handle_file.close()

size_row    = 28    # height of the image
size_col    = 28    # width of the image

num_image   = len(data)   #10000개
count       = 0     # count for the number of images

#
# normalize the values of the input data to be [0, 1]
#
def normalize(data):

    data_normalized = (data - min(data)) / (max(data) - min(data))

    return(data_normalized)

#
# example of distance function between two vectors x and y
#
def distance(x, y):

    d = (x - y) ** 2
    s = np.sum(d)
    # r = np.sqrt(s)

    return(s)

#
# make a matrix each column of which represents an images in a vector form
#
list_image  = np.empty((size_row * size_col, num_image), dtype=float)
list_label  = np.empty(num_image, dtype=int)

for line in data:

    line_data   = line.split(',')
    label       = line_data[0]
    im_vector   = np.asfarray(line_data[1:])
    im_vector   = normalize(im_vector)

    list_label[count]       = label       # size : 10000
    list_image[:, count]    = im_vector   # size : 784 * 10000

    count += 1

#
# plot first 150 images out of 10,000 with their labels
#
"""
f1 = plt.figure(1)

for i in range(150):

    label       = list_label[i]
    im_vector   = list_image[:, i]
    im_matrix   = im_vector.reshape((size_row, size_col))

    plt.subplot(10, 15, i+1)
    plt.title(label)
    plt.imshow(im_matrix, cmap='Greys', interpolation='None')

    frame   = plt.gca()
    frame.axes.get_xaxis().set_visible(False)
    frame.axes.get_yaxis().set_visible(False)


#plt.show()

#
# plot the average image of all the images for each digit
#
f2 = plt.figure(2)

im_average  = np.zeros((size_row * size_col, 10), dtype=float)
im_count    = np.zeros(10, dtype=int)

for i in range(num_image):

    im_average[:, list_label[i]] += list_image[:, i]
    im_count[list_label[i]] += 1

for i in range(10):

    im_average[:, i] /= im_count[i]

    plt.subplot(2, 5, i+1)
    plt.title(i)
    plt.imshow(im_average[:,i].reshape((size_row, size_col)), cmap='Greys', interpolation='None')

    frame   = plt.gca()
    frame.axes.get_xaxis().set_visible(False)
    frame.axes.get_yaxis().set_visible(False)

plt.show()
"""
print(num_image)  #10000
print(len(list_image))  #784
print(len(list_image[0]))  #10000
print(len(list_label))  #10000
#list_label 0~5999까지 training data, 6000~9999까지 test data
#list_image [:,5999]까지 training data, [:,9999]까지 test data

10000
784
10000
10000


In [0]:
def forward(x, theta):
  result = np.dot(x, theta)
  return result

In [0]:
def sigmoid(x):
  result = 1 / (1 + np.exp(-x))
  return result

In [23]:
def main():
  mu = 0
  sigma = 1ss
  theta_0 = np.random.normal(mu, sigma, size=(196,784)) 
  theta_1 = np.random.normal(mu, sigma, size=(49,196))   
  theta_2 = np.random.normal(mu, sigma, size=(10,49))   
  
  b_0 = np.random.normal(mu, sigma, 196)
  b_1 = np.random.normal(mu, sigma, 49)
  b_2 = np.random.normal(mu, sigma, 10)
 
  # y = theta*x + b
  #first layer
  # 196*10000 = (196*784)(784*10000)+(196*10000) -- 주의사항 : bias size가 (196*1)인 것을 10000개 복사하기!

if __name__ == "__main__":
  main()

[ 6.29269945e-01  8.11860345e-01 -1.78688125e-02  4.10187396e-01
 -6.13596335e-01 -2.91714056e-01 -6.69125927e-01 -9.13801854e-01
  1.56037581e-01 -5.59690851e-02 -5.93895455e-01  8.57727340e-01
  7.60535537e-01  7.57866518e-01  2.36362245e-01 -1.68558297e+00
 -2.05645994e+00  1.57269204e+00 -5.03440817e-01 -8.96181570e-02
 -1.16770231e+00  5.03834903e-01 -9.22539440e-01 -7.09938175e-01
  3.89251563e-01 -7.90835435e-01 -9.28580241e-01  1.51636259e-02
 -4.81227936e-01  8.91096686e-01 -1.42035738e+00 -1.71351330e+00
  6.36241614e-01 -9.01081810e-01 -6.79768257e-02 -5.59494938e-01
  2.11219044e+00 -8.18336430e-01 -1.06673116e+00  5.94113694e-01
 -1.69071980e-01  1.41036701e-03  7.85785235e-01  2.33357922e+00
 -8.88149845e-01  2.48383020e+00  3.55262836e-01  1.68519819e+00
 -4.89311128e-01 -2.41829048e-01  3.27545783e-01 -1.17391039e-01
 -5.69459349e-01  3.55801093e-01  3.31510351e-01 -2.22211545e+00
 -4.73039858e-01  5.87988531e-01 -3.66297861e-01  1.10663535e+00
  1.26182244e-01  5.16337

In [65]:
a = np.random.normal(0,1,size=(2,3))
b = np.random.normal(0,1,(2))
print(a)
print(b)
b = np.tile(b.T,3)
#print(b)
b= b.reshape(2,-1)
print(b)
c = np.add(a,b)
print(c)

[[-2.22194228 -0.48519178  0.65227499]
 [-0.0151791   0.06887266 -0.5789337 ]]
[-0.47558267 -0.64075162]
[[-0.47558267 -0.64075162 -0.47558267]
 [-0.64075162 -0.47558267 -0.64075162]]
[[-2.69752495 -1.1259434   0.17669232]
 [-0.65593071 -0.40671002 -1.21968531]]
